INSERT INTO PIZZA (`PIZZA_ID`,`PIZZA_NAME`,`PIZZA_PRICE`,`PIZZA_DESCRIPTION`) VALUES (1000,'Veg Pizza',6.12,'Chicken Pizza');
INSERT INTO PIZZA (`PIZZA_ID`,`PIZZA_NAME`,`PIZZA_PRICE`,`PIZZA_DESCRIPTION`) VALUES (1001,'Chicken Pizza',8.12,'Chicken Pizza');
INSERT INTO PIZZA (`PIZZA_ID`,`PIZZA_NAME`,`PIZZA_PRICE`,`PIZZA_DESCRIPTION`) VALUES (1002,'Pepperoni Pizza',10.12,'Chicken Pizza');


INSERT INTO PIZZA_SIZE (`PIZZA_SIZE_ID`,`PIZZA_SIZE_NAME`,`PIZZA_SIZE_PRICE`) VALUES (1,'Large',10.00);
INSERT INTO PIZZA_SIZE (`PIZZA_SIZE_ID`,`PIZZA_SIZE_NAME`,`PIZZA_SIZE_PRICE`) VALUES (2,'Medium ',8.00);
INSERT INTO PIZZA_SIZE (`PIZZA_SIZE_ID`,`PIZZA_SIZE_NAME`,`PIZZA_SIZE_PRICE`) VALUES (3,'Small',0.00);

INSERT INTO TOOPING (`TOOPING_ID`,`TOOPING_NAME`,`TOOPING_PRICE`,`TOOPING_DESCRIPTION`) VALUES (110,'Pepperoni',1.11,'Pepperoni');
INSERT INTO TOOPING (`TOOPING_ID`,`TOOPING_NAME`,`TOOPING_PRICE`,`TOOPING_DESCRIPTION`) VALUES (111,'Mushrooms',1.22,'Mushrooms');
INSERT INTO TOOPING (`TOOPING_ID`,`TOOPING_NAME`,`TOOPING_PRICE`,`TOOPING_DESCRIPTION`) VALUES (113,'Black olives',2.22,'Black olives');
INSERT INTO TOOPING (`TOOPING_ID`,`TOOPING_NAME`,`TOOPING_PRICE`,`TOOPING_DESCRIPTION`) VALUES (114,'Onions',1.00,'Onions');

INSERT INTO CRUST (`CUST_ID`,`CUST_NAME`,`CUST_PRICE`,`CUST_DESCIRIPTION`) VALUES (10,'Classic',2.22,'Classic Pizza');
INSERT INTO CRUST (`CUST_ID`,`CUST_NAME`,`CUST_PRICE`,`CUST_DESCIRIPTION`) VALUES (11,'Thin',1.22,'Thin Pizza');

